.travis.yml, meson.build, src/MainWindow.vala, src/Utils.vala, src/Views/AccountView.vala, src/meson.build, vapi/pwquality.vapi
Prototypes a "Create an Account" view. There is no meaningful account creation in this PR. The only functions in this UI are:
* password quality checking
* Username generation
* Username validity check
Looks like this:
=> Add New Account view

src/Views/AccountView.vala
=> AccountView: use an error revealer for confirm password

src/Views/AccountView.vala
Hopefully improve code readability
=> Entries store their own validity

src/Views/AccountView.vala
* One entry = one validation method
* Cache the result of validating an entry
* When an entry changes, check to see if entries are valid and if so set the finish button's sensitivity
=> AccountView.vala: Validate entire form

.travis.yml, data/io.elementary.initial-setup.policy, meson.build, src/Utils.vala, src/Views/AccountView.vala
Process must be executed with `pkexec` in order to have the necessary permissions
Terminal output claims that gpasswd fails, but going to the login screen determined that was a lie
=> Create a new user when pressing "Finish"

src/Views/AccountView.vala
=> AccountView: give real name entry focus

src/Views/LanguageView.vala
Should make it easier to evaluate/resolve conflicts with #48
=> LanguageView: change on_next_button_click to method

meson.build
Because this is annoying when it's not in order
=> Alphabetize Dependencies

src/Views/LanguageView.vala
Adds the country to the config so that you get a nice smart default selection in the keyboard layout view
=> LanguageView: Add country to config

.github/workflows/release.yml
Looks like we're mixing one-space and two-space
=> Release.yml: Use consistent two-space indentation

src/Config.vala.in, src/Helpers/LocaleHelper.vala, src/Objects/KeyboardLayout.vala, src/meson.build
Similar PRs in installer https://github.com/elementary/installer/pull/432 https://github.com/elementary/installer/pull/434
=> Honor XKB_CONFIG_ROOT environment variable, don't hardcode, fix isocodes

src/Views/AccountView.vala
Matches https://github.com/elementary/switchboard-plug-useraccounts/pull/143
=> AccountView: Adjust pw_levelbar values

.github/workflows/main.yml, README.md, meson.build, src/MainWindow.vala
The window can no longer be dragged around
=> MainWindow: Subclass Hdy.Window

src/Views/AccountView.vala
=> AccountView: Use Hdy.Avatar and bind to realname_entry

src/Views/KeyboardLayoutView.vala
The same fix with elementary/installer#510
=> Make titles consistent

src/Utils.vala, src/Views/AccountView.vala, src/Views/LanguageView.vala
* Rework some dialog copy to make it more human-readable
* Set dialog parents and make them modal
* Use `present ()` instead of `run ()` in preparation for Gtk4
=> Misc dialog cleanup

data/io.elementary.initial-setup.appdata.xml.in
* Make sure we use `description` tags
* Only keep 5 newest releases
=> Add release notes for 6.2.2

data/io.elementary.initial-setup.appdata.xml.in, meson.build
Contains a fix for the window being too small in Virtualbox.
=> Release 6.2.2

data/io.elementary.initial-setup.appdata.xml.in, src/Utils.vala, src/Views/AccountView.vala
* Create utility functions to throw dialogs
* Set the hostname before creating the account
* Use async when possible to not block the UI
* Do not keep the created_user object
=> AccountView: Refactor the account creation part

src/MainWindow.vala
Same as https://github.com/elementary/installer/pull/711
=> Prompt for screen reader shortcut after a timeout

debian/control
Same as https://github.com/elementary/installer/pull/712
Goes with #163
=> Control: Add espeak to depends

po/extra/POTFILES
Fixes the CI is failing: https://github.com/elementary/initial-setup/actions/runs/5801659266/job/15726389485
=> POTFILES: Correct metainfo filename

src/Views/KeyboardLayoutView.vala
box instead of grid
explicit margins
=> KeyboardLayoutView: Gtk4 prep, code style

src/Widgets/VariantWidget.vala
* Gtk4 prep
* Code style
* Variant title wraps instead of truncates
* grid instead of box
* use child property
=> VariantWidget: gtk4 prep

src/Views/LanguageView.vala
=> LanguageView: use Gtk.Gesture for secondary click

src/Views/AccountView.vala
Gtk4 prep and code style. Add input purpose hints
=> AccountView: Gtk4 prep

debian/control
=> Add iso-codes to build depends

src/Views/AccountView.vala
=> AccountView: set default widget

src/Application.vala
=> Application: granite.init

.github/workflows/main.yml, README.md, meson.build, src/Config.vala.in, src/Objects/KeyboardLayout.vala, src/meson.build, vapi/xkbregistry.vapi
Same improvements with https://github.com/elementary/installer/pull/833
=> KeyboardLayout: list from xkbregistry

.github/workflows/main.yml, README.md, meson.build, src/MainWindow.vala
Make sure Initial Setup stays centered
=> MainWindow: center on X11 and Wayland
